// Statement:
// Each new term in the Fibonacci sequence is generated by adding the previous 
// two terms. By starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
//
// By considering the terms in the Fibonacci sequence whose values do not exceed 
// four million, find the sum of the even-valued terms.


function fib() {

    const fibArray = [1,2]

    i = 2
    while (true) {
        
        fibArray[i] = fibArray[i - 1] + fibArray[i - 2]

        if (fibArray[i] > 4000000) {
            break
        }

        i ++
    }

    // iterate over fibArray and sum up only the even numbers
    const res = fibArray.reduce(
        (acc, currVal) => (currVal % 2 == 0 ? acc + currVal : acc), 0
    )
    return res
}

console.log(fib()) // 4613732